
Faker {
    locales: {
      az: {
        title: 'Azerbaijani',
        separator: ' və ',
        address: [Object],
        internet: [Object],
        name: [Object],
        phone_number: [Object],
        commerce: [Object],
        company: [Object],
        date: [Object]
      },
      ar: {
        title: 'Arabic',
        separator: ' & ',
        address: [Object],
        name: [Object],
        phone_number: [Object],
        cell_phone: [Object],
        commerce: [Object],
        vehicle: [Object],
        team: [Object],
        date: [Object]
      },
      cz: {
        title: 'Czech',
        address: [Object],
        company: [Object],
        internet: [Object],
        lorem: [Object],
        name: [Object],
        phone_number: [Object],
        date: [Object]
      },
      de: {
        title: 'German',
        address: [Object],
        company: [Object],
        internet: [Object],
        lorem: [Object],
        name: [Object],
        phone_number: [Object],
        cell_phone: [Object],
        date: [Object]
      },
      de_AT: {
        title: 'German (Austria)',
        address: [Object],
        company: [Object],
        internet: [Object],
        name: [Object],
        phone_number: [Object],
        cell_phone: [Object]
      },
      de_CH: {
        title: 'German (Switzerland)',
        address: [Object],
        company: [Object],
        internet: [Object],
        name: [Object],
        phone_number: [Object]
      },
      en: {
        title: 'English',
        separator: ' & ',
        address: [Object],
        animal: [Object],
        company: [Object],
        internet: [Object],
        database: [Object],
        lorem: [Object],
        name: [Object],
        phone_number: [Object],
        cell_phone: [Object],
        business: [Object],
        commerce: [Object],
        team: [Object],
        hacker: [Object],
        app: [Object],
        finance: [Object],
        date: [Object],
        system: [Object],
        vehicle: [Object],
        music: [Object]
      },
      en_AU: {
        title: 'English (Australia)',
        name: [Object],
        company: [Object],
        internet: [Object],
        address: [Object],
        phone_number: [Object]
      },
      en_AU_ocker: {
        title: 'English (Australia Ocker)',
        name: [Object],
        company: [Object],
        internet: [Object],
        address: [Object],
        phone_number: [Object]
      },
      en_BORK: { title: 'English (Bork)', lorem: [Object] },
      en_CA: {
        title: 'English (Canada)',
        address: [Object],
        internet: [Object],
        phone_number: [Object]
      },
      en_GB: {
        title: 'English (Great Britain)',
        address: [Object],
        internet: [Object],
        phone_number: [Object],
        cell_phone: [Object]
      },
      en_IE: {
        title: 'English (Ireland)',
        address: [Object],
        internet: [Object],
        phone_number: [Object],
        cell_phone: [Object]
      },
      en_IND: {
        title: 'English (India)',
        name: [Object],
        address: [Object],
        internet: [Object],
        company: [Object],
        phone_number: [Object]
      },
      en_US: {
        title: 'English (United States)',
        internet: [Object],
        address: [Object],
        phone_number: [Object]
      },
      en_ZA: {
        title: 'English (South Africa)',
        address: [Object],
        internet: [Object],
        name: [Object],
        phone_number: [Object],
        cell_phone: [Object],
        company: [Object]
      },
      es: {
        title: 'Spanish',
        address: [Object],
        company: [Object],
        internet: [Object],
        name: [Object],
        phone_number: [Object],
        cell_phone: [Object],
        commerce: [Object]
      },
      es_MX: {
        title: 'Spanish (Mexico)',
        separator: ' & ',
        name: [Object],
        address: [Object],
        company: [Object],
        internet: [Object],
        phone_number: [Object],
        cell_phone: [Object],
        lorem: [Object],
        commerce: [Object],
        team: [Object]
      },
      he: {
        title: 'Hebrew',
        separator: 'ו ',
        address: [Object],
        lorem: [Object],
        name: [Object],
        phone_number: [Object],
        cell_phone: [Object],
        commerce: [Object],
        date: [Object],
        music: [Object]
      },
      fa: {
        title: 'Farsi',
        name: [Object],
        address: [Object],
        phone_number: [Object],
        lorem: [Object],
        cell_phone: [Object],
        date: [Object],
        vehicle: [Object],
        internet: [Object],
        commerce: [Object],
        company: [Object],
        finance: [Object]
      },
      fi: { title: 'Finnish', name: [Object] },
      fr: {
        title: 'French',
        address: [Object],
        company: [Object],
        internet: [Object],
        lorem: [Object],
        name: [Object],
        phone_number: [Object],
        date: [Object]
      },
      fr_CA: {
        title: 'French (Canada)',
        address: [Object],
        internet: [Object],
        phone_number: [Object]
      },
      fr_CH: {
        title: 'French (Switzerland)',
        address: [Object],
        internet: [Object],
        phone_number: [Object]
      },
      ge: {
        title: 'Georgian',
        separator: ' და ',
        name: [Object],
        address: [Object],
        internet: [Object],
        company: [Object],
        phone_number: [Object],
        cell_phone: [Object]
      },
      hy: {
        title: 'Armenian',
        separator: ' և ',
        address: [Object],
        internet: [Object],
        lorem: [Object],
        name: [Object],
        phone_number: [Object],
        commerce: [Object],
        date: [Object]
      },
      hr: {
        title: 'Hrvatski',
        address: [Object],
        internet: [Object],
        name: [Object],
        phone_number: [Object],
        cell_phone: [Object],
        date: [Object]
      },
      id_ID: {
        title: 'Indonesia',
        address: [Object],
        company: [Object],
        internet: [Object],
        date: [Object],
        name: [Object],
        phone_number: [Object]
      },
      it: {
        title: 'Italian',
        address: [Object],
        company: [Object],
        internet: [Object],
        name: [Object],
        phone_number: [Object]
      },
      ja: {
        title: 'Japanese',
        address: [Object],
        phone_number: [Object],
        cell_phone: [Object],
        name: [Object],
        lorem: [Object]
      },
      ko: {
        title: 'Korean',
        address: [Object],
        phone_number: [Object],
        company: [Object],
        internet: [Object],
        lorem: [Object],
        name: [Object]
      },
      nb_NO: {
        title: 'Norwegian',
        address: [Object],
        company: [Object],
        internet: [Object],
        name: [Object],
        phone_number: [Object]
      },
      ne: {
        title: 'Nepalese',
        name: [Object],
        address: [Object],
        internet: [Object],
        company: [Object],
        phone_number: [Object]
      },
      nl: {
        title: 'Dutch',
        address: [Object],
        commerce: [Object],
        company: [Object],
        date: [Object],
        hacker: [Object],
        internet: [Object],
        lorem: [Object],
        name: [Object],
        phone_number: [Object]
      },
      nl_BE: {
        title: 'Dutch (Belgium)',
        address: [Object],
        company: [Object],
        internet: [Object],
        name: [Object],
        phone_number: [Object]
      },
      pl: {
        title: 'Polish',
        name: [Object],
        address: [Object],
        company: [Object],
        internet: [Object],
        lorem: [Object],
        phone_number: [Object],
        cell_phone: [Object]
      },
      pt_BR: {
        title: 'Portuguese (Brazil)',
        address: [Object],
        company: [Object],
        commerce: [Object],
        internet: [Object],
        lorem: [Object],
        name: [Object],
        phone_number: [Object],
        date: [Object]
      },
      pt_PT: {
        title: 'Portuguese (Portugal)',
        address: [Object],
        internet: [Object],
        name: [Object],
        phone_number: [Object],
        cell_phone: [Object],
        commerce: [Object],
        date: [Object]
      },
      ro: {
        title: 'Romanian',
        address: [Object],
        cell_phone: [Object],
        date: [Object],
        internet: [Object],
        name: [Object],
        phone_number: [Object]
      },
      ru: {
        title: 'Russian',
        separator: ' и ',
        address: [Object],
        internet: [Object],
        lorem: [Object],
        name: [Object],
        phone_number: [Object],
        commerce: [Object],
        company: [Object],
        date: [Object],
        hacker: [Object]
      },
      sk: {
        title: 'Slovakian',
        address: [Object],
        company: [Object],
        internet: [Object],
        lorem: [Object],
        name: [Object],
        phone_number: [Object]
      },
      sv: {
        title: 'Swedish',
        address: [Object],
        company: [Object],
        internet: [Object],
        name: [Object],
        phone_number: [Object],
        cell_phone: [Object],
        commerce: [Object],
        team: [Object],
        date: [Object]
      },
      tr: {
        title: 'Turkish',
        address: [Object],
        internet: [Object],
        lorem: [Object],
        phone_number: [Object],
        cell_phone: [Object],
        name: [Object]
      },
      uk: {
        title: 'Ukrainian',
        address: [Object],
        company: [Object],
        internet: [Object],
        name: [Object],
        phone_number: [Object]
      },
      vi: {
        title: 'Vietnamese',
        address: [Object],
        internet: [Object],
        phone_number: [Object],
        cell_phone: [Object],
        name: [Object],
        company: [Object],
        lorem: [Object],
        date: [Object]
      },
      zh_CN: {
        title: 'Chinese',
        address: [Object],
        name: [Object],
        phone_number: [Object]
      },
      zh_TW: {
        title: 'Chinese (Taiwan)',
        address: [Object],
        name: [Object],
        phone_number: [Object]
      }
    },
    locale: 'en',
    localeFallback: 'en',
    definitions: {
      name: {},
      address: {},
      animal: {},
      company: {},
      lorem: {},
      hacker: {},
      phone_number: {},
      finance: {},
      internet: {},
      commerce: {},
      database: {},
      system: {},
      date: {},
      vehicle: {},
      music: {},
      title: '',
      separator: ''
    },
    fake: [Function: fake],
    unique: [Function: unique],
    mersenne: Mersenne {
      rand: [Function (anonymous)],
      seed: [Function (anonymous)],
      seed_array: [Function (anonymous)]
    },
    random: Random {
      number: [Function (anonymous)],
      float: [Function (anonymous)],
      arrayElement: [Function (anonymous)],
      arrayElements: [Function (anonymous)],
      objectElement: [Function (anonymous)],
      uuid: [Function (anonymous)],
      boolean: [Function (anonymous)],
      word: [Function: randomWord],
      words: [Function: randomWords],
      image: [Function: randomImage],
      locale: [Function: randomLocale],
      alpha: [Function: alpha],
      alphaNumeric: [Function: alphaNumeric],
      hexaDecimal: [Function: hexaDecimal]
    },
    helpers: Helpers {
      randomize: [Function (anonymous)],
      slugify: [Function (anonymous)],
      replaceSymbolWithNumber: [Function (anonymous)],
      replaceSymbols: [Function (anonymous)],
      replaceCreditCardSymbols: [Function (anonymous)],
      repeatString: [Function (anonymous)],
      regexpStyleStringParse: [Function (anonymous)],
      shuffle: [Function (anonymous)],
      mustache: [Function (anonymous)],
      createCard: [Function (anonymous)],
      contextualCard: [Function (anonymous)],
      userCard: [Function (anonymous)],
      createTransaction: [Function (anonymous)]
    },
    name: Name {
      firstName: [Function (anonymous)],
      lastName: [Function (anonymous)],
      middleName: [Function (anonymous)],
      findName: [Function (anonymous)],
      jobTitle: [Function (anonymous)],
      gender: [Function (anonymous)],
      prefix: [Function (anonymous)],
      suffix: [Function (anonymous)],
      title: [Function (anonymous)],
      jobDescriptor: [Function (anonymous)],
      jobArea: [Function (anonymous)],
      jobType: [Function (anonymous)]
    },
    address: Address {
      zipCode: [Function (anonymous)],
      zipCodeByState: [Function (anonymous)],
      city: [Function (anonymous)],
      cityPrefix: [Function (anonymous)],
      citySuffix: [Function (anonymous)],
      cityName: [Function (anonymous)],
      streetName: [Function (anonymous)],
      streetAddress: [Function (anonymous)],
      streetSuffix: [Function (anonymous)],
      streetPrefix: [Function (anonymous)],
      secondaryAddress: [Function (anonymous)],
      county: [Function (anonymous)],
      country: [Function (anonymous)],
      countryCode: [Function (anonymous)],
      state: [Function (anonymous)],
      stateAbbr: [Function (anonymous)],
      latitude: [Function (anonymous)],
      longitude: [Function (anonymous)],
      direction: [Function (anonymous)] { schema: [Object] },
      cardinalDirection: [Function (anonymous)] { schema: [Object] },
      ordinalDirection: [Function (anonymous)] { schema: [Object] },
      nearbyGPSCoordinate: [Function (anonymous)],
      timeZone: [Function (anonymous)]
    },
    animal: Animal {
      dog: [Function (anonymous)],
      cat: [Function (anonymous)],
      snake: [Function (anonymous)],
      bear: [Function (anonymous)],
      lion: [Function (anonymous)],
      cetacean: [Function (anonymous)],
      horse: [Function (anonymous)],
      bird: [Function (anonymous)],
      cow: [Function (anonymous)],
      fish: [Function (anonymous)],
      crocodilia: [Function (anonymous)],
      insect: [Function (anonymous)],
      rabbit: [Function (anonymous)],
      type: [Function (anonymous)]
    },
    company: Company {
      suffixes: [Function (anonymous)],
      companyName: [Function (anonymous)],
      companySuffix: [Function (anonymous)],
      catchPhrase: [Function (anonymous)],
      bs: [Function (anonymous)],
      catchPhraseAdjective: [Function (anonymous)],
      catchPhraseDescriptor: [Function (anonymous)],
      catchPhraseNoun: [Function (anonymous)],
      bsAdjective: [Function (anonymous)],
      bsBuzz: [Function (anonymous)],
      bsNoun: [Function (anonymous)]
    },
    finance: Finance {
      account: [Function (anonymous)],
      accountName: [Function (anonymous)],
      routingNumber: [Function (anonymous)],
      mask: [Function (anonymous)],
      amount: [Function (anonymous)],
      transactionType: [Function (anonymous)],
      currencyCode: [Function (anonymous)],
      currencyName: [Function (anonymous)],
      currencySymbol: [Function (anonymous)],
      bitcoinAddress: [Function (anonymous)],
      litecoinAddress: [Function (anonymous)],
      creditCardNumber: [Function (anonymous)],
      creditCardCVV: [Function (anonymous)],
      ethereumAddress: [Function (anonymous)],
      iban: [Function (anonymous)],
      bic: [Function (anonymous)],
      transactionDescription: [Function (anonymous)]
    },
    image: Image {
      image: [Function (anonymous)],
      avatar: [Function (anonymous)],
      imageUrl: [Function (anonymous)],
      abstract: [Function (anonymous)],
      animals: [Function (anonymous)],
      business: [Function (anonymous)],
      cats: [Function (anonymous)],
      city: [Function (anonymous)],
      food: [Function (anonymous)],
      nightlife: [Function (anonymous)],
      fashion: [Function (anonymous)],
      people: [Function (anonymous)],
      nature: [Function (anonymous)],
      sports: [Function (anonymous)],
      technics: [Function (anonymous)],
      transport: [Function (anonymous)],
      dataUri: [Function (anonymous)],
      lorempixel: Lorempixel {
        image: [Function (anonymous)],
        avatar: [Function (anonymous)],
        imageUrl: [Function (anonymous)],
        abstract: [Function (anonymous)],
        animals: [Function (anonymous)],
        business: [Function (anonymous)],
        cats: [Function (anonymous)],
        city: [Function (anonymous)],
        food: [Function (anonymous)],
        nightlife: [Function (anonymous)],
        fashion: [Function (anonymous)],
        people: [Function (anonymous)],
        nature: [Function (anonymous)],
        sports: [Function (anonymous)],
        technics: [Function (anonymous)],
        transport: [Function (anonymous)]
      },
      unsplash: Unsplash {
        image: [Function (anonymous)],
        avatar: [Function (anonymous)],
        imageUrl: [Function (anonymous)],
        food: [Function (anonymous)],
        people: [Function (anonymous)],
        nature: [Function (anonymous)],
        technology: [Function (anonymous)],
        objects: [Function (anonymous)],
        buildings: [Function (anonymous)]
      },
      lorempicsum: LoremPicsum {
        image: [Function (anonymous)],
        imageGrayscale: [Function (anonymous)],
        imageBlurred: [Function (anonymous)],
        imageRandomSeeded: [Function (anonymous)],
        avatar: [Function (anonymous)],
        imageUrl: [Function (anonymous)]
      }
    },
    lorem: Lorem {
      word: [Function (anonymous)],
      words: [Function (anonymous)],
      sentence: [Function (anonymous)],
      slug: [Function (anonymous)],
      sentences: [Function (anonymous)],
      paragraph: [Function (anonymous)],
      paragraphs: [Function (anonymous)],
      text: [Function: loremText],
      lines: [Function: lines]
    },
    hacker: Hacker {
      abbreviation: [Function (anonymous)],
      adjective: [Function (anonymous)],
      noun: [Function (anonymous)],
      verb: [Function (anonymous)],
      ingverb: [Function (anonymous)],
      phrase: [Function (anonymous)]
    },
    internet: Internet {
      avatar: [Function (anonymous)] { schema: [Object] },
      email: [Function (anonymous)] { schema: [Object] },
      exampleEmail: [Function (anonymous)],
      userName: [Function (anonymous)] { schema: [Object] },
      protocol: [Function (anonymous)] { schema: [Object] },
      httpMethod: [Function (anonymous)] { schema: [Object] },
      url: [Function (anonymous)] { schema: [Object] },
      domainName: [Function (anonymous)] { schema: [Object] },
      domainSuffix: [Function (anonymous)] { schema: [Object] },
      domainWord: [Function (anonymous)] { schema: [Object] },
      ip: [Function (anonymous)] { schema: [Object] },
      ipv6: [Function (anonymous)] { schema: [Object] },
      port: [Function (anonymous)] { schema: [Object] },
      userAgent: [Function (anonymous)] { schema: [Object] },
      color: [Function (anonymous)] { schema: [Object] },
      mac: [Function (anonymous)] { schema: [Object] },
      password: [Function (anonymous)] { schema: [Object] }
    },
    database: Database {
      column: [Function (anonymous)] { schema: [Object] },
      type: [Function (anonymous)] { schema: [Object] },
      collation: [Function (anonymous)] { schema: [Object] },
      engine: [Function (anonymous)] { schema: [Object] }
    },
    phone: Phone {
      phoneNumber: [Function (anonymous)],
      phoneNumberFormat: [Function (anonymous)],
      phoneFormats: [Function (anonymous)]
    },
    date: _Date {
      past: [Function (anonymous)],
      future: [Function (anonymous)],
      between: [Function (anonymous)],
      betweens: [Function (anonymous)],
      recent: [Function (anonymous)],
      soon: [Function (anonymous)],
      month: [Function (anonymous)],
      weekday: [Function (anonymous)]
    },
    time: _Time { recent: [Function (anonymous)] },
    commerce: Commerce {
      color: [Function (anonymous)],
      department: [Function (anonymous)],
      productName: [Function (anonymous)],
      price: [Function (anonymous)],
      productAdjective: [Function (anonymous)],
      productMaterial: [Function (anonymous)],
      product: [Function (anonymous)],
      productDescription: [Function (anonymous)]
    },
    system: System {
      fileName: [Function (anonymous)],
      commonFileName: [Function (anonymous)],
      mimeType: [Function (anonymous)],
      commonFileType: [Function (anonymous)],
      commonFileExt: [Function (anonymous)],
      fileType: [Function (anonymous)],
      fileExt: [Function (anonymous)],
      directoryPath: [Function (anonymous)],
      filePath: [Function (anonymous)],
      semver: [Function (anonymous)]
    },
    git: Git {
      branch: [Function (anonymous)],
      commitEntry: [Function (anonymous)],
      commitMessage: [Function (anonymous)],
      commitSha: [Function (anonymous)],
      shortSha: [Function (anonymous)]
    },
    vehicle: Vehicle {
      vehicle: [Function (anonymous)] { schema: [Object] },
      manufacturer: [Function (anonymous)] { schema: [Object] },
      model: [Function (anonymous)] { schema: [Object] },
      type: [Function (anonymous)] { schema: [Object] },
      fuel: [Function (anonymous)] { schema: [Object] },
      vin: [Function (anonymous)] { schema: [Object] },
      color: [Function (anonymous)] { schema: [Object] },
      vrm: [Function (anonymous)] { schema: [Object] },
      bicycle: [Function (anonymous)] { schema: [Object] }
    },
    music: Music { genre: [Function (anonymous)] { schema: [Object] } },       
    datatype: Datatype {
      number: [Function (anonymous)],
      float: [Function (anonymous)],
      datetime: [Function (anonymous)],
      string: [Function (anonymous)],
      uuid: [Function (anonymous)],
      boolean: [Function (anonymous)],
      hexaDecimal: [Function: hexaDecimal],
      json: [Function: json],
      array: [Function: array]
    }
  }